spring.application.name: product-composite-service
server.port: 7001
server.error.include-message: always
app:
  product-service:
    host: localhost
    port: 7002
  recommendation-service:
    host: localhost
    port: 7003
  review-service:
    host: localhost
    port: 7004
logging:
  level:
    root: INFO
    com.vishnu: DEBUG
---
spring.config.activate.on-profile: docker
server.port: 8080
app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080
