spring.application.name: review-service
server.port: 7004
server.error.include-message: always
logging:
  level:
    root: INFO
    com.vishnu: DEBUG
---
spring.config.activate.on-profile: docker
server.port: 8080